name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: [self-hosted, codespaces-fcf711]  # Target your specific runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy index.html to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./  # The directory containing index.html
